export type QuestionIntelligenceErrorCode =
  | "ANALYSIS_SESSION_NOT_FOUND"
  | "ANALYSIS_SESSION_STATE_INVALID"
  | "TRANSCRIPT_SEGMENT_INVALID"
  | "TRANSCRIPT_SEGMENT_NOT_FINAL"
  | "TRANSCRIPT_SEGMENT_DUPLICATE"
  | "TRANSCRIPT_SEGMENT_SEQUENCE_CONFLICT"
  | "QUESTION_CANDIDATE_NOT_FOUND"
  | "QUESTION_CANDIDATE_INVALID"
  | "QUESTION_BOUNDARY_SESSION_INVALID"
  | "QUESTION_BOUNDARY_STALE_REVISION"
  | "QUESTION_BOUNDARY_ACTION_DUPLICATE"
  | "QUESTION_BOUNDARY_SEQUENCE_CONFLICT"
  | "QUESTION_BOUNDARY_SEMANTIC_FAILED"
  | "FINALIZED_QUESTION_NOT_FOUND"
  | "FINALIZED_QUESTION_PREVIOUS_NOT_FOUND"
  | "FINALIZED_QUESTION_ALREADY_UNDONE";

export class QuestionIntelligenceError extends Error {
  constructor(
    public readonly code: QuestionIntelligenceErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "QuestionIntelligenceError";
  }
}
