export type UploadedAudioErrorCode =
  | "UPLOADED_AUDIO_DISABLED"
  | "UPLOADED_AUDIO_FILE_REQUIRED"
  | "UPLOADED_AUDIO_TYPE_UNSUPPORTED"
  | "UPLOADED_AUDIO_CONTENT_INVALID"
  | "UPLOADED_AUDIO_SIZE_INVALID"
  | "UPLOADED_AUDIO_NOT_FOUND"
  | "UPLOADED_AUDIO_SESSION_NOT_FOUND"
  | "UPLOADED_AUDIO_SESSION_INVALID"
  | "UPLOADED_AUDIO_ACTION_DUPLICATE"
  | "UPLOADED_AUDIO_TRANSCRIPTION_BUSY"
  | "UPLOADED_AUDIO_TRANSCRIPTION_LEGACY_ACTION"
  | "UPLOADED_AUDIO_TRANSCRIPTION_FAILED"
  | "UPLOADED_AUDIO_WORKER_UNAVAILABLE"
  | "UPLOADED_AUDIO_DELETION_BUSY"
  | "UPLOADED_AUDIO_DELETION_INCOMPLETE"
  | "UPLOADED_AUDIO_PROVIDER_DISABLED"
  | "UPLOADED_AUDIO_PATH_UNSAFE"
  | "UPLOADED_AUDIO_STORAGE_FAILED";

export class UploadedAudioError extends Error {
  constructor(
    public readonly code: UploadedAudioErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "UploadedAudioError";
  }
}
